/*
 MIT
*/
(function(y){"function"===typeof define&&define.amd?define(y):"undefined"!=typeof module&&"undefined"!=typeof module.exports?module.exports=y():window.Sortable=y()})(function(){function y(a,b){if(!a||!a.nodeType||1!==a.nodeType)throw"Sortable: `el` must be HTMLElement, not "+{}.toString.call(a);this.el=a;this.options=b=pa({},b);a[H]=this;var c={group:null,sort:!0,disabled:!1,store:null,handle:null,scroll:!0,scrollSensitivity:30,scrollSpeed:10,bubbleScroll:!0,draggable:/[uo]l/i.test(a.nodeName)?">li":
">*",swapThreshold:1,invertSwap:!1,invertedSwapThreshold:null,removeCloneOnHide:!0,direction:function(){return Ha(a,this.options)},ghostClass:"sortable-ghost",chosenClass:"sortable-chosen",dragClass:"sortable-drag",ignore:"a, img",filter:null,preventOnFilter:!0,animation:0,easing:null,setData:function(a,b){a.setData("Text",b.textContent)},dropBubble:!1,dragoverBubble:!1,dataIdAttr:"data-id",delay:0,touchStartThreshold:w(window.devicePixelRatio,10)||1,forceFallback:!1,fallbackClass:"sortable-fallback",
fallbackOnBody:!1,fallbackTolerance:0,fallbackOffset:{x:0,y:0},supportPointer:!1!==y.supportPointer&&("PointerEvent"in window||window.navigator&&"msPointerEnabled"in window.navigator),emptyInsertThreshold:5},e;for(e in c)e in b||(b[e]=c[e]);Ia(b);for(var d in this)"_"===d.charAt(0)&&"function"===typeof this[d]&&(this[d]=this[d].bind(this));if(this.nativeDraggable=b.forceFallback?!1:bb)this.options.touchStartThreshold=1;b.supportPointer?q(a,"pointerdown",this._onTapStart):(q(a,"mousedown",this._onTapStart),
q(a,"touchstart",this._onTapStart));this.nativeDraggable&&(q(a,"dragover",this),q(a,"dragenter",this));O.push(this.el);b.store&&b.store.get&&this.sort(b.store.get(this)||[])}function E(a,b,c,e){if(a){c=c||h;do{if(null!=b&&(">"===b[0]&&a.parentNode===c&&Ja(a,b.substring(1))||Ja(a,b))||e&&a===c)return a;if(a===c)break}while(a=a.host&&a!==h&&a.host.nodeType?a.host:a.parentNode)}return null}function q(a,b,c){a.addEventListener(b,c,Ka)}function n(a,b,c){a.removeEventListener(b,c,Ka)}function I(a,b,c){if(a&&
b)if(a.classList)a.classList[c?"add":"remove"](b);else{var e=(" "+a.className+" ").replace(La," ").replace(" "+b+" "," ");a.className=(e+(c?" "+b:"")).replace(La," ")}}function m(a,b,c){var e=a&&a.style;if(e){if(void 0===c)return h.defaultView&&h.defaultView.getComputedStyle?c=h.defaultView.getComputedStyle(a,""):a.currentStyle&&(c=a.currentStyle),void 0===b?c:c[b];b in e||-1!==b.indexOf("webkit")||(b="-webkit-"+b);e[b]=c+("string"===typeof c?"":"px")}}function ea(a){var b="";do{var c=m(a,"transform");
c&&"none"!==c&&(b=c+" "+b)}while(a=a.parentNode);if(window.DOMMatrix)return new DOMMatrix(b);if(window.WebKitCSSMatrix)return new WebKitCSSMatrix(b);if(window.CSSMatrix)return new CSSMatrix(b)}function Ma(a,b,c){if(a){a=a.getElementsByTagName(b);b=0;var e=a.length;if(c)for(;b<e;b++)c(a[b],b);return a}return[]}function F(a,b,c,e,d,f,A,k,m){a=a||b[H];var D=a.options,l="on"+c.charAt(0).toUpperCase()+c.substr(1);if(!window.CustomEvent||J||X){var L=h.createEvent("Event");L.initEvent(c,!0,!0)}else L=new CustomEvent(c,
{bubbles:!0,cancelable:!0});L.to=d||b;L.from=f||b;L.item=e||b;L.clone=p;L.oldIndex=A;L.newIndex=k;L.originalEvent=m;L.pullMode=G?G.lastPutMode:void 0;b&&b.dispatchEvent(L);D[l]&&D[l].call(a,L)}function Na(a,b,c,e,d,f,A,k){var D=a[H],l=D.options.onMove,m;if(!window.CustomEvent||J||X){var g=h.createEvent("Event");g.initEvent("move",!0,!0)}else g=new CustomEvent("move",{bubbles:!0,cancelable:!0});g.to=b;g.from=a;g.dragged=c;g.draggedRect=e;g.related=d||b;g.relatedRect=f||z(b);g.willInsertAfter=k;g.originalEvent=
A;a.dispatchEvent(g);l&&(m=l.call(D,g,A));return m}function qa(a){a.draggable=!1}function cb(){ra=!1}function sa(a,b,c){for(var e=0,d=0,D=a.children;d<D.length;){if("none"!==D[d].style.display&&D[d]!==g&&D[d]!==f&&E(D[d],c.draggable,a,!1)){if(e===b)return D[d];e++}d++}return null}function ta(a){for(a=a.lastElementChild;a&&(a===g||"none"===a.style.display);)a=a.previousElementSibling;return a||null}function db(a,b,c){var e=z(ta(c));c="vertical"===b?a.clientY:a.clientX;a="vertical"===b?a.clientX:a.clientY;
var d="vertical"===b?e.bottom:e.right,f="vertical"===b?e.left:e.top;e="vertical"===b?e.right:e.bottom;return"vertical"===b?a>e+10||a<=e&&c>d&&a>=f:c>d&&a>f||c<=d&&a>e+10}function eb(a,b,c,e,d,D,A){var k=z(b);a="vertical"===c?a.clientY:a.clientX;var h="vertical"===c?k.height:k.width,g="vertical"===c?k.top:k.left;c="vertical"===c?k.bottom:k.right;z(f);k=!1;if(!D)if(A&&fa<h*e)if(!Y&&(1===Z?a>g+h*d/2:a<c-h*d/2)&&(Y=!0),Y)k=!0;else{if(1===Z?a<g+fa:a>c-fa)return-1*Z}else if(a>g+h*(1-e)/2&&a<c-h*(1-e)/2)return Oa(b);
if(k||D)if(a<g+h*d/2||a>c-h*d/2)return a>g+h/2?1:-1;return 0}function Oa(a){var b=Q(f);a=Q(a);return b<a?1:-1}function fb(a){a=a.tagName+a.className+a.src+a.href+a.textContent;for(var b=a.length,c=0;b--;)c+=a.charCodeAt(b);return c.toString(36)}function Q(a,b){b=0;if(!a||!a.parentNode)return-1;for(;a&&(a=a.previousElementSibling);)"TEMPLATE"!==a.nodeName.toUpperCase()&&a!==p&&b++;return b}function Ja(a,b){if(a)try{if(a.matches)return a.matches(b);if(a.msMatchesSelector)return a.msMatchesSelector(b);
if(a.webkitMatchesSelector)return a.webkitMatchesSelector(b)}catch(c){}return!1}function Pa(a,b){return function(){if(!aa){var c=arguments,e=this;aa=S(function(){1===c.length?a.call(e,c[0]):a.apply(e,c);aa=void 0},b)}}}function pa(a,b){if(a&&b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function Qa(a){return ua&&ua.dom?ua.dom(a).cloneNode(!0):Ra?Ra(a).clone(!0)[0]:a.cloneNode(!0)}function gb(a){ha.length=0;a=a.getElementsByTagName("input");for(var b=a.length;b--;){var c=a[b];c.checked&&
ha.push(c)}}function ia(a){return S(a,0)}function z(a,b,c,e){if(a.getBoundingClientRect||a===K){if(a!==K&&a!==M()){var d=a.getBoundingClientRect();var f=d.top;var A=d.left;var k=d.bottom;var h=d.right;var g=d.height;var l=d.width}else A=f=0,k=window.innerHeight,h=window.innerWidth,g=window.innerHeight,l=window.innerWidth;if(e&&a!==K&&(c=c||a.parentNode,!J)){do if(c&&c.getBoundingClientRect&&"none"!==m(c,"transform")){k=c.getBoundingClientRect();f-=k.top+w(m(c,"border-top-width"));A-=k.left+w(m(c,
"border-left-width"));k=f+d.height;h=A+d.width;break}while(c=c.parentNode)}b&&a!==K&&(b=(a=ea(c||a))&&a.a,c=a&&a.d,a&&(f/=c,A/=b,l/=b,g/=c,k=f+g,h=A+l));return{top:f,left:A,bottom:k,right:h,width:l,height:g}}}function Sa(a,b){var c=P(a,!0);for(a=z(a)[b];c;){var e=z(c)[b];if(!("top"===b||"left"===b?a>=e:a<=e))return c;if(c===M())break;c=P(c,!1)}return!1}function Ta(a){var b=0,c=0,e=M();if(a){do{var d=ea(a),f=d.d;b+=a.scrollLeft*d.a;c+=a.scrollTop*f}while(a!==e&&(a=a.parentNode))}return[b,c]}if("undefined"===
typeof window||!window.document)return function(){throw Error("Sortable.js requires a window with a document");};var f,x,g,p,l,R,va,ba,wa,xa,t,v,ja,G,r=[],ya=!1,ca=!1,ka=!1,O=[],T,za,Aa,da,B,la,U,Z,Y=!1,ma=!1,V,fa,u,Ba=[],W,La=/\s+/g,H="Sortable"+(new Date).getTime(),K=window,h=K.document,w=K.parseInt,S=K.setTimeout,Ra=K.jQuery||K.Zepto,ua=K.Polymer,Ka={capture:!1,passive:!1},J=!!navigator.userAgent.match(/(?:Trident.*rv[ :]?11\.|msie|iemobile)/i),X=!!navigator.userAgent.match(/Edge/i),Ua=!!navigator.userAgent.match(/firefox/i),
Ca=!(!navigator.userAgent.match(/safari/i)||navigator.userAgent.match(/chrome/i)||navigator.userAgent.match(/android/i)),na=!!navigator.userAgent.match(/iP(ad|od|hone)/i),Va=X||J?"cssFloat":"float",bb="draggable"in h.createElement("div"),Da=function(){if(J)return!1;var a=h.createElement("x");a.style.cssText="pointer-events:auto";return"auto"===a.style.pointerEvents}(),ra=!1,Ea=!1,N=Math.abs,hb=Math.min,ib=Math.max,ha=[],Ha=function(a,b){var c=m(a),e=w(c.width)-w(c.paddingLeft)-w(c.paddingRight)-w(c.borderLeftWidth)-
w(c.borderRightWidth),d=sa(a,0,b);a=sa(a,1,b);var f=d&&m(d);b=a&&m(a);var A=f&&w(f.marginLeft)+w(f.marginRight)+z(d).width,k=b&&w(b.marginLeft)+w(b.marginRight)+z(a).width;return"flex"===c.display?"column"===c.flexDirection||"column-reverse"===c.flexDirection?"vertical":"horizontal":"grid"===c.display?1>=c.gridTemplateColumns.split(" ").length?"vertical":"horizontal":d&&"none"!==f.float?(c="left"===f.float?"left":"right",!a||"both"!==b.clear&&b.clear!==c?"horizontal":"vertical"):d&&("block"===f.display||
"flex"===f.display||"table"===f.display||"grid"===f.display||A>=e&&"none"===c[Va]||a&&"none"===c[Va]&&A+k>e)?"vertical":"horizontal"},jb=function(a,b,c,e,d){c=z(c);d="vertical"===e?c.right:c.bottom;a="vertical"===e?a:b;return("vertical"===e?c.left:c.top)<a&&a<d},kb=function(a,b,c){var e=a===f&&W||z(a),d=b===f&&W||z(b);b="vertical"===c?e.left:e.top;a="vertical"===c?e.right:e.bottom;e="vertical"===c?e.width:e.height;var D="vertical"===c?d.left:d.top,A="vertical"===c?d.right:d.bottom;c="vertical"===
c?d.width:d.height;return b===D||a===A||b+e/2===D+c/2},P=function(a,b){if(!a||!a.getBoundingClientRect)return M();var c=!1;do if(a.clientWidth<a.scrollWidth||a.clientHeight<a.scrollHeight){var e=m(a);if(a.clientWidth<a.scrollWidth&&("auto"==e.overflowX||"scroll"==e.overflowX)||a.clientHeight<a.scrollHeight&&("auto"==e.overflowY||"scroll"==e.overflowY)){if(!a||!a.getBoundingClientRect||a===h.body)break;if(c||b)return a;c=!0}}while(a=a.parentNode);return M()},M=function(){return J?h.documentElement:
h.scrollingElement},Wa=function(a,b,c){a.scrollLeft+=b;a.scrollTop+=c},Fa=Pa(function(a,b,c,e){if(b.scroll){var d=c?c[H]:window,f=b.scrollSensitivity,A=b.scrollSpeed,k=a.clientX,h=a.clientY,g=M(),l=!1;wa!==c&&(oa(),ba=b.scroll,xa=b.scrollFn,!0===ba&&(wa=ba=P(c,!0)));c=0;var q=ba;do{var n=q,p=z(n),u=p.top,C=p.bottom,x=p.left,G=p.right,v=p.width;p=p.height;var E=n.scrollWidth;var F=n.scrollHeight;var t=m(n);var I=n.scrollLeft;var w=n.scrollTop;if(n===g){var J=v<E&&("auto"===t.overflowX||"scroll"===
t.overflowX||"visible"===t.overflowX);t=p<F&&("auto"===t.overflowY||"scroll"===t.overflowY||"visible"===t.overflowY)}else J=v<E&&("auto"===t.overflowX||"scroll"===t.overflowX),t=p<F&&("auto"===t.overflowY||"scroll"===t.overflowY);x=J&&(N(G-k)<=f&&I+v<E)-(N(x-k)<=f&&!!I);u=t&&(N(C-h)<=f&&w+p<F)-(N(u-h)<=f&&!!w);if(!r[c])for(C=0;C<=c;C++)r[C]||(r[C]={});if(r[c].vx!=x||r[c].vy!=u||r[c].el!==n)r[c].el=n,r[c].vx=x,r[c].vy=u,clearInterval(r[c].pid),!n||0==x&&0==u||(l=!0,r[c].pid=setInterval(function(){e&&
0===this.layer&&(y.active._emulateDragOver(!0),y.active._onTouchMove(B,!0));var b=r[this.layer].vy?r[this.layer].vy*A:0,c=r[this.layer].vx?r[this.layer].vx*A:0;"function"===typeof xa&&"continue"!==xa.call(d,c,b,a,B,r[this.layer].el)||Wa(r[this.layer].el,c,b)}.bind({layer:c}),24));c++}while(b.bubbleScroll&&q!==g&&(q=P(q,!1)));ya=l}},30),oa=function(){r.forEach(function(a){clearInterval(a.pid)});r=[]},Ia=function(a){function b(a,c){return function(d,e,f,h){var k=d.options.group.name&&e.options.group.name&&
d.options.group.name===e.options.group.name;if(null==a&&(c||k))return!0;if(null==a||!1===a)return!1;if(c&&"clone"===a)return a;if("function"===typeof a)return b(a(d,e,f,h),c)(d,e,f,h);d=(c?d:e).options.group.name;return!0===a||"string"===typeof a&&a===d||a.join&&-1<a.indexOf(d)}}var c={},e=a.group;e&&"object"==typeof e||(e={name:e});c.name=e.name;c.checkPull=b(e.pull,!0);c.checkPut=b(e.put);c.revertClone=e.revertClone;a.group=c},Xa=function(a){f&&f.parentNode&&f.parentNode[H]&&f.parentNode[H]._computeIsAligned(a)},
Ya=function(a,b){for(;!b[H];)b=b.parentNode;return a===b},Za=function(a,b,c){for(a=a.parentNode;a&&!a[H];)a=a.parentNode;if(a)a[H][c](pa(b,{artificialBubble:!0}))},$a=function(){!Da&&g&&m(g,"display","none")},ab=function(){!Da&&g&&m(g,"display","")};h.addEventListener("click",function(a){if(ka)return a.preventDefault(),a.stopPropagation&&a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),ka=!1},!0);var Ga=function(a){a=a.touches?a.touches[0]:a;if(f){a:{var b=a.clientX;for(var c=
a.clientY,e=0;e<O.length;e++)if(!ta(O[e])){var d=z(O[e]),h=O[e][H].options.emptyInsertThreshold,g=c>=d.top-h&&c<=d.bottom+h;if(b>=d.left-h&&b<=d.right+h&&g){b=O[e];break a}}b=void 0}b&&b[H]._onDragOver({clientX:a.clientX,clientY:a.clientY,target:b,rootEl:b})}};q(h,"dragover",Ga);q(h,"mousemove",Ga);q(h,"touchmove",Ga);y.prototype={constructor:y,_computeIsAligned:function(a){if(g&&!Da){$a();var b=h.elementFromPoint(a.clientX,a.clientY);ab()}else b=a.target;b=E(b,this.options.draggable,this.el,!1);
if(!Ea&&f&&f.parentNode===this.el){for(var c=this.el.children,e=0;e<c.length;e++)E(c[e],this.options.draggable,this.el,!1)&&c[e]!==b&&(c[e].sortableMouseAligned=jb(a.clientX,a.clientY,c[e],this._getDirection(a,null),this.options));E(b,this.options.draggable,this.el,!0)||(U=null);Ea=!0;S(function(){Ea=!1},30)}},_getDirection:function(a,b){return"function"===typeof this.options.direction?this.options.direction.call(this,a,b,f):this.options.direction},_onTapStart:function(a){if(a.cancelable){var b=this,
c=this.el,e=this.options,d=e.preventOnFilter,h=a.type,g=a.touches&&a.touches[0],k=(g||a).target,l=a.target.shadowRoot&&(a.path&&a.path[0]||a.composedPath&&a.composedPath()[0])||k,m=e.filter;gb(c);if(!(J&&!a.artificialBubble&&!Ya(c,k)||f||/mousedown|pointerdown/.test(h)&&0!==a.button||e.disabled||l.isContentEditable))if(k=E(k,e.draggable,c,!1),!k)J&&Za(c,a,"_onTapStart");else if(va!==k){var n=Q(k,e.draggable);if("function"===typeof m){if(m.call(this,a,k,this)){F(b,l,"filter",k,c,c,n);d&&a.cancelable&&
a.preventDefault();return}}else if(m&&(m=m.split(",").some(function(a){if(a=E(l,a.trim(),c,!1))return F(b,a,"filter",k,c,c,n),!0}))){d&&a.cancelable&&a.preventDefault();return}e.handle&&!E(l,e.handle,c,!1)||this._prepareDragStart(a,g,k,n)}}},_handleAutoScroll:function(a,b){if(f&&this.options.scroll){var c=a.clientX,e=a.clientY,d=h.elementFromPoint(c,e),g=this;if(b||X||J||Ca){Fa(a,g.options,d,b);var l=P(d,!0);!ya||T&&c===za&&e===Aa||(T&&clearInterval(T),T=setInterval(function(){if(f){var d=P(h.elementFromPoint(c,
e),!0);d!==l&&(l=d,oa(),Fa(a,g.options,l,b))}},10),za=c,Aa=e)}else g.options.bubbleScroll&&P(d,!0)!==M()?Fa(a,g.options,P(d,!1),!1):oa()}},_prepareDragStart:function(a,b,c,e){var d=this,h=d.el,g=d.options,k=h.ownerDocument;c&&!f&&c.parentNode===h&&(l=h,f=c,x=f.parentNode,R=f.nextSibling,va=c,ja=g.group,t=e,da={target:f,clientX:(b||a).clientX,clientY:(b||a).clientY},this._lastX=(b||a).clientX,this._lastY=(b||a).clientY,f.style["will-change"]="all",f.style.transition="",f.style.transform="",c=function(){d._disableDelayedDragEvents();
!Ua&&d.nativeDraggable&&(f.draggable=!0);d._triggerDragStart(a,b);F(d,l,"choose",f,l,l,t);I(f,g.chosenClass,!0)},g.ignore.split(",").forEach(function(a){Ma(f,a.trim(),qa)}),g.supportPointer?q(k,"pointerup",d._onDrop):(q(k,"mouseup",d._onDrop),q(k,"touchend",d._onDrop),q(k,"touchcancel",d._onDrop)),Ua&&this.nativeDraggable&&(this.options.touchStartThreshold=4,f.draggable=!0),!g.delay||this.nativeDraggable&&(X||J)?c():(q(k,"mouseup",d._disableDelayedDrag),q(k,"touchend",d._disableDelayedDrag),q(k,"touchcancel",
d._disableDelayedDrag),q(k,"mousemove",d._delayedDragTouchMoveHandler),q(k,"touchmove",d._delayedDragTouchMoveHandler),g.supportPointer&&q(k,"pointermove",d._delayedDragTouchMoveHandler),d._dragStartTimer=S(c,g.delay)))},_delayedDragTouchMoveHandler:function(a){a=a.touches?a.touches[0]:a;ib(N(a.clientX-this._lastX),N(a.clientY-this._lastY))>=Math.floor(this.options.touchStartThreshold/(this.nativeDraggable&&window.devicePixelRatio||1))&&this._disableDelayedDrag()},_disableDelayedDrag:function(){f&&
qa(f);clearTimeout(this._dragStartTimer);this._disableDelayedDragEvents()},_disableDelayedDragEvents:function(){var a=this.el.ownerDocument;n(a,"mouseup",this._disableDelayedDrag);n(a,"touchend",this._disableDelayedDrag);n(a,"touchcancel",this._disableDelayedDrag);n(a,"mousemove",this._delayedDragTouchMoveHandler);n(a,"touchmove",this._delayedDragTouchMoveHandler);n(a,"pointermove",this._delayedDragTouchMoveHandler)},_triggerDragStart:function(a,b){b=b||("touch"==a.pointerType?a:null);!this.nativeDraggable||
b?this.options.supportPointer?q(h,"pointermove",this._onTouchMove):b?q(h,"touchmove",this._onTouchMove):q(h,"mousemove",this._onTouchMove):(q(f,"dragend",this),q(l,"dragstart",this._onDragStart));try{h.selection?ia(function(){h.selection.empty()}):window.getSelection().removeAllRanges()}catch(c){}},_dragStarted:function(a,b){ca=!1;if(l&&f){this.nativeDraggable&&(q(h,"dragover",this._handleAutoScroll),q(h,"dragover",Xa));var c=this.options;!a&&I(f,c.dragClass,!1);I(f,c.ghostClass,!0);m(f,"transform",
"");y.active=this;a&&this._appendGhost();F(this,l,"start",f,l,l,t,void 0,b)}else this._nulling()},_emulateDragOver:function(a){if(B&&(this._lastX!==B.clientX||this._lastY!==B.clientY||a)){this._lastX=B.clientX;this._lastY=B.clientY;$a();for(var b=a=h.elementFromPoint(B.clientX,B.clientY);a&&a.shadowRoot;)b=a=a.shadowRoot.elementFromPoint(B.clientX,B.clientY);if(b){do{if(b[H]&&b[H]._onDragOver({clientX:B.clientX,clientY:B.clientY,target:a,rootEl:b})&&!this.options.dragoverBubble)break;a=b}while(b=
b.parentNode)}f.parentNode[H]._computeIsAligned(B);ab()}},_onTouchMove:function(a,b){if(da){var c=this.options,e=c.fallbackTolerance,d=c.fallbackOffset;c=a.touches?a.touches[0]:a;var f=g&&ea(g),h=g&&f&&f.a;f=g&&f&&f.d;var k=na&&u&&Ta(u);h=(c.clientX-da.clientX+d.x)/(h||1)+(k?k[0]-Ba[0]:0)/(h||1);d=(c.clientY-da.clientY+d.y)/(f||1)+(k?k[1]-Ba[1]:0)/(f||1);d=a.touches?"translate3d("+h+"px,"+d+"px,0)":"translate("+h+"px,"+d+"px)";if(!y.active&&!ca){if(e&&hb(N(c.clientX-this._lastX),N(c.clientY-this._lastY))<
e)return;this._onDragStart(a,!0)}!b&&this._handleAutoScroll(c,!0);la=!0;B=c;m(g,"webkitTransform",d);m(g,"mozTransform",d);m(g,"msTransform",d);m(g,"transform",d);a.cancelable&&a.preventDefault()}},_appendGhost:function(){if(!g){var a=this.options.fallbackOnBody?h.body:l,b=z(f,!0,a,!na);m(f);var c=this.options;if(na){for(u=a;"static"===m(u,"position")&&"none"===m(u,"transform")&&u!==h;)u=u.parentNode;if(u!==h){var e=z(u,!0);b.top-=e.top;b.left-=e.left}u!==h.body&&u!==h.documentElement?(u===h&&(u=
M()),b.top+=u.scrollTop,b.left+=u.scrollLeft):u=M();Ba=Ta(u)}g=f.cloneNode(!0);I(g,c.ghostClass,!1);I(g,c.fallbackClass,!0);I(g,c.dragClass,!0);m(g,"box-sizing","border-box");m(g,"margin",0);m(g,"top",b.top);m(g,"left",b.left);m(g,"width",b.width);m(g,"height",b.height);m(g,"opacity","0.8");m(g,"position",na?"absolute":"fixed");m(g,"zIndex","100000");m(g,"pointerEvents","none");a.appendChild(g)}},_onDragStart:function(a,b){var c=this,e=a.dataTransfer,d=c.options;p=Qa(f);p.draggable=!1;p.style["will-change"]=
"";this._hideClone();I(p,c.options.chosenClass,!1);c._cloneId=ia(function(){c.options.removeCloneOnHide||l.insertBefore(p,f);F(c,l,"clone",f)});!b&&I(f,d.dragClass,!0);b?(ka=!0,c._loopId=setInterval(c._emulateDragOver,50)):(n(h,"mouseup",c._onDrop),n(h,"touchend",c._onDrop),n(h,"touchcancel",c._onDrop),e&&(e.effectAllowed="move",d.setData&&d.setData.call(c,e,f)),q(h,"drop",c),m(f,"transform","translateZ(0)"));ca=!0;c._dragStartId=ia(c._dragStarted.bind(c,b,a));q(h,"selectstart",c);Ca&&m(h.body,"user-select",
"none")},_onDragOver:function(a){function b(b){b&&(q?p._hideClone():p._showClone(r),p&&(I(f,G?G.options.ghostClass:p.options.ghostClass,!1),I(f,k.ghostClass,!0)),G!==r&&r!==y.active?G=r:r===y.active&&(G=null),B&&r._animate(B,f),d&&g&&r._animate(g,d));if(d===f&&!f.animated||d===e&&!d.animated)U=null;k.dragoverBubble||a.rootEl||d===h||(r._handleAutoScroll(a),f.parentNode[H]._computeIsAligned(a));!k.dragoverBubble&&a.stopPropagation&&a.stopPropagation();return!0}function c(){F(r,l,"change",d,e,l,t,Q(f,
k.draggable),a)}var e=this.el,d=a.target,g,m,k=this.options,n=k.group,p=y.active,q=ja===n,u=k.sort,r=this;if(!ra&&(!J||a.rootEl||a.artificialBubble||Ya(e,d))){void 0!==a.preventDefault&&a.cancelable&&a.preventDefault();la=!0;d=E(d,k.draggable,e,!0);if(E(a.target,null,f,!0)||d.animated)return b(!1);d!==f&&(ka=!1);if(p&&!k.disabled&&(q?u||(m=!l.contains(f)):G===this||(this.lastPutMode=ja.checkPull(this,p,f,a))&&n.checkPut(this,p,f,a))){var v=this._getDirection(a,d);var B=z(f);if(m)return this._hideClone(),
x=l,R?l.insertBefore(f,R):l.appendChild(f),b(!0);m=ta(e);if(!m||db(a,v,e)&&!m.animated){if(m&&e===a.target&&(d=m),d&&(g=z(d)),q?p._hideClone():p._showClone(this),!1!==Na(l,e,f,B,d,g,a,!!d))return e.appendChild(f),x=e,W=null,c(),b(!0)}else if(d&&d!==f&&d.parentNode===e){var C=0;C=d.sortableMouseAligned;var w=f.parentNode!==e;m="vertical"===v?"top":"left";u=(n=Sa(d,"top")||Sa(f,"top"))?n.scrollTop:void 0;if(U!==d){V=null;var K=z(d)[m];Y=!1}kb(f,d,v)&&C||w||n||k.invertSwap||"insert"===V||"swap"===V?
("swap"!==V&&(ma=k.invertSwap||w),C=eb(a,d,v,k.swapThreshold,null==k.invertedSwapThreshold?k.swapThreshold:k.invertedSwapThreshold,ma,U===d),V="swap"):(C=Oa(d),V="insert");if(0===C)return b(!1);W=null;U=d;Z=C;g=z(d);v=d.nextElementSibling;w=!1;w=1===C;C=Na(l,e,f,B,d,g,a,w);if(!1!==C){if(1===C||-1===C)w=1===C;ra=!0;S(cb,30);q?p._hideClone():p._showClone(this);w&&!v?e.appendChild(f):d.parentNode.insertBefore(f,w?v:d);n&&Wa(n,0,u-n.scrollTop);x=f.parentNode;void 0===K||ma||(fa=N(K-z(d)[m]));c();return b(!0)}}if(e.contains(f))return b(!1)}J&&
!a.rootEl&&Za(e,a,"_onDragOver");return!1}},_animate:function(a,b){var c=this.options.animation;if(c){var e=z(b);b===f&&(W=e);1===a.nodeType&&(a=z(a));if(a.left+a.width/2!==e.left+e.width/2||a.top+a.height/2!==e.top+e.height/2){var d=ea(this.el),g=d&&d.a;d=d&&d.d;m(b,"transition","none");m(b,"transform","translate3d("+(a.left-e.left)/(g?g:1)+"px,"+(a.top-e.top)/(d?d:1)+"px,0)");m(b,"transition","transform "+c+"ms"+(this.options.easing?" "+this.options.easing:""));m(b,"transform","translate3d(0,0,0)")}"number"===
typeof b.animated&&clearTimeout(b.animated);b.animated=S(function(){m(b,"transition","");m(b,"transform","");b.animated=!1},c)}},_offUpEvents:function(){var a=this.el.ownerDocument;n(h,"touchmove",this._onTouchMove);n(h,"pointermove",this._onTouchMove);n(a,"mouseup",this._onDrop);n(a,"touchend",this._onDrop);n(a,"pointerup",this._onDrop);n(a,"touchcancel",this._onDrop);n(h,"selectstart",this)},_onDrop:function(a){var b=this.el,c=this.options;Y=ma=ya=ca=!1;clearInterval(this._loopId);clearInterval(T);
oa();clearTimeout(aa);aa=void 0;clearTimeout(this._dragStartTimer);clearTimeout(this._cloneId);clearTimeout(this._dragStartId);n(h,"mousemove",this._onTouchMove);this.nativeDraggable&&(n(h,"drop",this),n(b,"dragstart",this._onDragStart),n(h,"dragover",this._handleAutoScroll),n(h,"dragover",Xa));Ca&&m(h.body,"user-select","");this._offUpEvents();if(a&&(la&&(a.cancelable&&a.preventDefault(),!c.dropBubble&&a.stopPropagation()),g&&g.parentNode&&g.parentNode.removeChild(g),(l===x||G&&"clone"!==G.lastPutMode)&&
p&&p.parentNode&&p.parentNode.removeChild(p),f&&(this.nativeDraggable&&n(f,"dragend",this),qa(f),f.style["will-change"]="",I(f,G?G.options.ghostClass:this.options.ghostClass,!1),I(f,this.options.chosenClass,!1),F(this,l,"unchoose",f,x,l,t,null,a),l!==x?(v=Q(f,c.draggable),0<=v&&(F(null,x,"add",f,x,l,t,v,a),F(this,l,"remove",f,x,l,t,v,a),F(null,x,"sort",f,x,l,t,v,a),F(this,l,"sort",f,x,l,t,v,a)),G&&G.save()):f.nextSibling!==R&&(v=Q(f,c.draggable),0<=v&&(F(this,l,"update",f,x,l,t,v,a),F(this,l,"sort",
f,x,l,t,v,a))),y.active))){if(null==v||-1===v)v=t;F(this,l,"end",f,x,l,t,v,a);this.save()}this._nulling()},_nulling:function(){l=f=x=g=R=p=va=ba=wa=r.length=T=za=Aa=da=B=la=v=t=U=Z=W=G=ja=y.active=null;ha.forEach(function(a){a.checked=!0});ha.length=0},handleEvent:function(a){switch(a.type){case "drop":case "dragend":this._onDrop(a);break;case "dragenter":case "dragover":f&&(this._onDragOver(a),a.dataTransfer&&(a.dataTransfer.dropEffect="move"),a.cancelable&&a.preventDefault());break;case "selectstart":a.preventDefault()}},
toArray:function(){for(var a=[],b,c=this.el.children,e=0,d=c.length,f=this.options;e<d;e++)b=c[e],E(b,f.draggable,this.el,!1)&&a.push(b.getAttribute(f.dataIdAttr)||fb(b));return a},sort:function(a){var b={},c=this.el;this.toArray().forEach(function(a,d){d=c.children[d];E(d,this.options.draggable,c,!1)&&(b[a]=d)},this);a.forEach(function(a){b[a]&&(c.removeChild(b[a]),c.appendChild(b[a]))})},save:function(){var a=this.options.store;a&&a.set&&a.set(this)},closest:function(a,b){return E(a,b||this.options.draggable,
this.el,!1)},option:function(a,b){var c=this.options;if(void 0===b)return c[a];c[a]=b;"group"===a&&Ia(c)},destroy:function(){var a=this.el;a[H]=null;n(a,"mousedown",this._onTapStart);n(a,"touchstart",this._onTapStart);n(a,"pointerdown",this._onTapStart);this.nativeDraggable&&(n(a,"dragover",this),n(a,"dragenter",this));Array.prototype.forEach.call(a.querySelectorAll("[draggable]"),function(a){a.removeAttribute("draggable")});this._onDrop();O.splice(O.indexOf(this.el),1);this.el=a=null},_hideClone:function(){p.cloneHidden||
(m(p,"display","none"),p.cloneHidden=!0,p.parentNode&&this.options.removeCloneOnHide&&p.parentNode.removeChild(p))},_showClone:function(a){"clone"!==a.lastPutMode?this._hideClone():p.cloneHidden&&(l.contains(f)&&!this.options.group.revertClone?l.insertBefore(p,f):R?l.insertBefore(p,R):l.appendChild(p),this.options.group.revertClone&&this._animate(f,p),m(p,"display",""),p.cloneHidden=!1)}};var aa;q(h,"touchmove",function(a){(y.active||ca)&&a.cancelable&&a.preventDefault()});y.utils={on:q,off:n,css:m,
find:Ma,is:function(a,b){return!!E(a,b,a,!1)},extend:pa,throttle:Pa,closest:E,toggleClass:I,clone:Qa,index:Q,nextTick:ia,cancelNextTick:function(a){return clearTimeout(a)},detectDirection:Ha,getChild:sa};y.create=function(a,b){return new y(a,b)};y.version="1.8.4";return y});
